commandlinefu_id: 5640
translator:
  weibo: Spacewander__罗泽轩
command: |-
  for i in $(find ~/.config/chromium/*/Extensions -name 'manifest.json'); do n=$(grep -hIr name $i| cut -f4 -d '"'| sort);u="https://chrome.google.com/extensions/detail/";ue=$(basename $(dirname $(dirname $i))); echo -e "$n:\n$u$ue\n" ; done
summary: |-
  列出你安装的Chromium版本(连同到对应版本页面的url)
