commandlinefu_id: 2360
translator:
  weibo: ''
hide: true
command: |-
  ifconfig eth0 down hw ether (newmacaddresshere) && ifconfig eth0 up && ifconfig eth0 (newipaddresshere) netmask 255.255.255.0 up && /bin/hostname (newhostnamehere)
summary: |-
  Mac, ip, and hostname change - sweet!
