commandlinefu_id: 13361
translator:
  weibo: ''
hide: true
command: |-
  ifconfig |grep HWaddr |cut -d ' ' -f 1,11 |grep eth0 |cut -d ' ' -f 2|xargs | awk -F':' '{ print $1$2$3$4$5$6 }'
summary: |-
  Get MAC ID linux command line
