commandlinefu_id: 381
translator:
  weibo: ''
hide: true
command: |-
  sed -n 's/[ :]/_/g; s/^\(.\{1,\}\)_5_\($1$[$./0-9A-Za-z]\{27,31\}\)_*$/\1:\2/p' < cisco-device-config > passwd
summary: |-
  Format a password file for John the Ripper from Cisco configs  (Level 5)
