commandlinefu_id: 6373
translator:
  weibo: ''
hide: true
command: |-
  st() { LDFLAGS=-static CFLAGS=-static CXXFLAGS=-static NOSHARED=yes ./configure $@ ;} usage: st [configure operands]
summary: |-
  static compilation
