#!/bin/bash

# the script's pwd is the root dir of the local repository

SCRIPT=tool/set_translator_weibo_and_show.sh
LIST=`git status -s |grep "M .*\.yaml" | cut -d ' ' -f 3`

for f in $LIST;do
    if [ -f $f ]; then
		grep "weibo: ''" $f >/dev/null 2>&1
		if [ $? -eq 0 ] # find it
		then 
			echo "pre-commit hook error:"
			echo "you should run $SCRIPT before you commit"
			exit 1
		fi
    fi
done
